-- Notas fiscais (gestão administrativa) + contratos — aplicar uma vez
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS fiscal_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NULL,
  document_kind VARCHAR(32) NOT NULL COMMENT 'product_out,service,consumer,purchase_in',
  client_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NULL,
  document_number VARCHAR(64) NULL,
  series VARCHAR(16) NULL,
  access_key VARCHAR(44) NULL,
  issued_at DATETIME NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft' COMMENT 'draft,issued,cancelled,voided,error',
  subtotal_amount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  discount_total DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  total_amount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  notes TEXT NULL,
  xml_path VARCHAR(512) NULL,
  pdf_path VARCHAR(512) NULL,
  purchase_order_id BIGINT UNSIGNED NULL,
  nature_entry_id BIGINT UNSIGNED NULL,
  cfop_entry_id BIGINT UNSIGNED NULL,
  model_entry_id BIGINT UNSIGNED NULL,
  series_entry_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_fd_company_kind (company_id, document_kind),
  KEY idx_fd_status (company_id, status),
  KEY idx_fd_issued (issued_at),
  KEY idx_fd_client (client_id),
  KEY idx_fd_supplier (supplier_id),
  KEY idx_fd_store (store_id),
  CONSTRAINT fk_fd_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  CONSTRAINT fk_fd_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE SET NULL,
  CONSTRAINT fk_fd_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE SET NULL,
  CONSTRAINT fk_fd_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET @fkpo := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'fiscal_documents' AND CONSTRAINT_NAME = 'fk_fd_purchase_order');
SET @sql := IF(@fkpo = 0 AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = 'purchase_orders'),
  'ALTER TABLE fiscal_documents ADD CONSTRAINT fk_fd_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) ON DELETE SET NULL', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

CREATE TABLE IF NOT EXISTS fiscal_document_lines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  fiscal_document_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NULL,
  service_id BIGINT UNSIGNED NULL,
  description VARCHAR(512) NULL,
  qty DECIMAL(14,4) NOT NULL DEFAULT 1.0000,
  unit_price DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  line_discount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  line_total DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_fdl_doc (fiscal_document_id),
  CONSTRAINT fk_fdl_doc FOREIGN KEY (fiscal_document_id) REFERENCES fiscal_documents (id) ON DELETE CASCADE,
  CONSTRAINT fk_fdl_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL,
  CONSTRAINT fk_fdl_service FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_services (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NULL,
  contract_number VARCHAR(64) NULL,
  client_id BIGINT UNSIGNED NOT NULL,
  service_id BIGINT UNSIGNED NULL,
  description TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  amount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  adjustment_note VARCHAR(255) NULL,
  periodicity_entry_id BIGINT UNSIGNED NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active' COMMENT 'active,suspended,closed,cancelled',
  notes TEXT NULL,
  attachment_path VARCHAR(512) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_cs_company (company_id),
  KEY idx_cs_client (client_id),
  KEY idx_cs_status (company_id, status),
  CONSTRAINT fk_cs_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  CONSTRAINT fk_cs_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE SET NULL,
  CONSTRAINT fk_cs_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT,
  CONSTRAINT fk_cs_service FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_rentals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NULL,
  contract_number VARCHAR(64) NULL,
  client_id BIGINT UNSIGNED NOT NULL,
  asset_description VARCHAR(512) NULL,
  description TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  amount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  deposit_amount DECIMAL(14,4) NULL,
  periodicity_entry_id BIGINT UNSIGNED NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active' COMMENT 'active,suspended,closed,cancelled',
  notes TEXT NULL,
  attachment_path VARCHAR(512) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_cr_company (company_id),
  KEY idx_cr_client (client_id),
  CONSTRAINT fk_cr_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  CONSTRAINT fk_cr_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE SET NULL,
  CONSTRAINT fk_cr_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_subscriptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NULL,
  subscription_number VARCHAR(64) NULL,
  client_id BIGINT UNSIGNED NOT NULL,
  plan_description VARCHAR(512) NULL,
  recurring_amount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  periodicity_entry_id BIGINT UNSIGNED NULL,
  start_date DATE NULL,
  next_billing_date DATE NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active' COMMENT 'active,suspended,closed,cancelled',
  notes TEXT NULL,
  attachment_path VARCHAR(512) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_csub_company (company_id),
  KEY idx_csub_client (client_id),
  CONSTRAINT fk_csub_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  CONSTRAINT fk_csub_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE SET NULL,
  CONSTRAINT fk_csub_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
